# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisBlender
                                 A QGIS plugin
 This plugin prepares DEMs for use in Blender.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ben Leamon
        email                : ben.leamon@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import tempfile
import processing
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QListWidgetItem
from qgis.core import (
    QgsProject, 
    QgsRasterLayer,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsMessageLog, 
    Qgis,
    QgsApplication,
    )

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .qgis_blender_dialog import QgisBlenderDialog


class QgisBlender:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QgisBlender_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QGIS2Blender')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Plugin Defaults
        self.default_gdal_args = {
            "merge": "",
            "warp": "",
            "clip": "",
            "translate": "-co COMPRESS=LZW -co TILED=YES"
        }

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QgisBlender', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/qgis_blender/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Prepare DEMs for Blender'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&QGIS2Blender'),
                action)
            self.iface.removeToolBarIcon(action)

    # Helper methods
    def ensure_proj_db(self):
        """Ensure PROJ can find proj.db for GDAL tools spawned by Processing."""
        if getattr(self, "_proj_ready", False):
            return

        # 1) If user/system already configured PROJ correctly, do nothing
        for var in ("PROJ_DATA", "PROJ_LIB"):
            p = os.environ.get(var)
            if p and os.path.exists(os.path.join(p, "proj.db")):
                self._proj_ready = True
                return

        # 2) Try QGIS-provided locations (portable)
        candidates = []
        try:
            candidates.append(os.path.join(QgsApplication.pkgDataPath(), "proj"))
            # common on some installs
            candidates.append(os.path.join(QgsApplication.prefixPath(), "share", "proj"))
        except Exception:
            pass

        # 3) Pick the first candidate that actually contains proj.db
        proj_dir = None
        for c in candidates:
            if c and os.path.exists(os.path.join(c, "proj.db")):
                proj_dir = c
                break

        if not proj_dir:
            raise RuntimeError(
                "Could not locate proj.db. Set PROJ_DATA to the folder containing proj.db "
                "or check your QGIS installation."
            )

        # 4) Set env vars for this QGIS session (inherited by gdalwarp subprocesses)
        os.environ.setdefault("PROJ_DATA", proj_dir)
        os.environ.setdefault("PROJ_LIB", proj_dir)  # compatibility

        QgsMessageLog.logMessage(
            f"Configured PROJ for session: PROJ_DATA={os.environ.get('PROJ_DATA')}",
            "QGIS2Blender",
            Qgis.Info
        )
        self._proj_ready = True

    def populate_raster_list(self):
        """Fill the dialog list with raster layers from the current project."""
        # Start by clearing the list
        self.dlg.listWidget_rasters.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsRasterLayer):
                item = QListWidgetItem(layer.name())
                item.setData(Qt.UserRole, layer)
                self.dlg.listWidget_rasters.addItem(item)

    def populate_default_args(self):
        """Populate the dialog with default values"""
        self.dlg.plainTextEdit_merge_args.setPlainText(self.default_gdal_args["merge"])
        self.dlg.plainTextEdit_warp_args.setPlainText(self.default_gdal_args["warp"])
        self.dlg.plainTextEdit_clip_args.setPlainText(self.default_gdal_args["clip"])
        self.dlg.plainTextEdit_translate_args.setPlainText(self.default_gdal_args["translate"])

    def browse_output(self):
        """Open a save dialog and put the path into the output line"""
        path, _ = QFileDialog.getSaveFileName(
            self.dlg,
            "Save output GeoTIFF",
            "",
            "GeoTIFF (*.tif *.tiff)"
        )

        if path: 
            if not path.lower().endswith(('.tif', '.tiff')):
                path += ".tif"
            self.dlg.lineEdit_output.setText(path)
            
    def read_selected_rasters(self):
        items = self.dlg.listWidget_rasters.selectedItems()
        return [it.data(Qt.UserRole) for it in items]
    
    def read_step_args(self):
        return {
            "merge": self.dlg.plainTextEdit_merge_args.toPlainText().strip(),
            "warp": self.dlg.plainTextEdit_warp_args.toPlainText().strip(),
            "clip": self.dlg.plainTextEdit_clip_args.toPlainText().strip(),
            "translate": self.dlg.plainTextEdit_translate_args.toPlainText().strip(),
        }
    
    def build_vrt(self, raster_layers, workdir, merge_extra_args: str):
        """
        Build a virtual raster from 2+ input rasters and return the path.
        Uses gdal:buildvirtualraster.
        """
        sources = [layer.source() for layer in raster_layers]
        vrt_path = os.path.join(workdir, "00_mosaic.vrt")

        params = {
            "INPUT": sources,
            "RESOLUTION": 0,
            "SEPARATE": False,
            "OUTPUT": vrt_path,
        }

        merge_extra_args = (merge_extra_args or "").strip()
        if merge_extra_args:
            params["EXTRA"] = merge_extra_args

        res_vrt = processing.run("gdal:buildvirtualraster", params)
        QgsMessageLog.logMessage(f"VRT result: {res_vrt}", "QGIS2Blender", Qgis.Info)

        vrt_out = res_vrt.get("OUTPUT", vrt_path)
        if not os.path.exists(vrt_out):
            raise RuntimeError(f"VRT step did not create output: {vrt_out}")

        return vrt_out
    
    def compute_target_extent(self, target_crs):
        """Transform current canvas extent into the target CRS."""
        canvas = self.iface.mapCanvas()
        canvas_extent = canvas.extent()

        project = QgsProject.instance()
        canvas_crs = canvas.mapSettings().destinationCrs()

        xform = QgsCoordinateTransform(canvas_crs, target_crs, project)
        return xform.transformBoundingBox(canvas_extent)

    def step_warp(self, input_path, target_crs, warp_args, output_path):
        """Reproject input raster/VRT into target CRS."""
        warp_params = {
            "INPUT": input_path,
            "TARGET_CRS": target_crs.authid(),
            "EXTRA": warp_args,
            "OUTPUT": output_path,
        }

        res_warp = processing.run("gdal:warpreproject", warp_params)
        QgsMessageLog.logMessage(f"Warp result: {res_warp}", "QGIS2Blender", Qgis.Info)

        warp_out_actual = res_warp.get("OUTPUT", output_path)
        if not os.path.exists(warp_out_actual):
            raise RuntimeError(
                f"Warp step did not create output: {warp_out_actual}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return warp_out_actual
    
    def step_clip(self, input_path, target_extent, clip_args, output_path):
        """Clip raster by transformed canvas extent."""
        extent_str = (
            f"{target_extent.xMinimum()},"
            f"{target_extent.xMaximum()},"
            f"{target_extent.yMinimum()},"
            f"{target_extent.yMaximum()}"
        )

        clip_params = {
            "INPUT": input_path,
            "PROJWIN": extent_str,
            "EXTRA": clip_args,
            "OUTPUT": output_path,
        }

        res_clip = processing.run("gdal:cliprasterbyextent", clip_params)
        QgsMessageLog.logMessage(f"Clip result: {res_clip}", "QGIS2Blender", Qgis.Info)

        clip_out_actual = res_clip.get("OUTPUT", output_path)
        if not os.path.exists(clip_out_actual):
            raise RuntimeError(
                f"Clip step did not create output: {clip_out_actual}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return clip_out_actual

    def step_translate(self, input_path, translate_args, output_path):
        """Translate clipped raster to final output path."""
        translate_params = {
            "INPUT": input_path,
            "EXTRA": translate_args,
            "OUTPUT": output_path,
        }

        res_translate = processing.run("gdal:translate", translate_params)
        QgsMessageLog.logMessage(f"Translate result: {res_translate}", "QGIS2Blender", Qgis.Info)

        final_out = res_translate.get("OUTPUT", output_path)
        if not os.path.exists(final_out):
            raise RuntimeError(
                f"Translate step did not create output: {final_out}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return final_out


    def pipeline_v1(self, raster_layers, out_path: str, target_crs_text: str):
        """
        Version 1 pipeline:
        optional VRT -> warp -> clip -> translate
        """
        self.ensure_proj_db()
        step_args = self.read_step_args()

        target_crs = QgsCoordinateReferenceSystem(target_crs_text)
        if not target_crs.isValid():
            raise ValueError(f"Invalid CRS: '{target_crs_text}'. Please use an EPSG code.")

        workdir = tempfile.mkdtemp(prefix="qgis_blender_")
        QgsMessageLog.logMessage(f"Workdir: {workdir}", "QGIS2Blender", Qgis.Info)
        QgsMessageLog.logMessage(f"Target CRS: {target_crs.authid()}", "QGIS2Blender", Qgis.Info)

        # Decide what feeds the warp step
        if len(raster_layers) == 1:
            warp_input = raster_layers[0].source()
        else:
            warp_input = self.build_vrt(raster_layers, workdir, step_args["merge"])

        target_extent = self.compute_target_extent(target_crs)

        warp_out = os.path.join(workdir, "01_warp.tif")
        clip_out = os.path.join(workdir, "02_clip.tif")

        warped = self.step_warp(warp_input, target_crs, step_args["warp"], warp_out)
        clipped = self.step_clip(warped, target_extent, step_args["clip"], clip_out)
        final_out = self.step_translate(clipped, step_args["translate"], out_path)

        out_layer = QgsRasterLayer(final_out, os.path.basename(final_out))
        if not out_layer.isValid():
            raise RuntimeError("Output file was written but QGIS could not load it as a raster layer.")

        QgsProject.instance().addMapLayer(out_layer)
        self.iface.messageBar().pushSuccess("QGIS2Blender", "Created output and added to project.")

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QgisBlenderDialog()
            # Populate defaults 
            self.populate_default_args()

            # Connect dialog buttons to widgets
            self.dlg.pushButton_browse.clicked.connect(self.browse_output)

        # Refresh the list of rasters each time the dialog opens
        self.populate_raster_list()
        # show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        # See if OK was pressed
        if result:
            rasters = self.read_selected_rasters()
            out_path = self.dlg.lineEdit_output.text().strip()
            target_crs = self.dlg.lineEdit_target_crs.text().strip()
            # TK I think this line can be removed. 
            #step_args = self.read_step_args()

            if not rasters:
                self.iface.messageBar().pushWarning("QgisBlender", "Select at least one raster layer.")
                return
            if not out_path:
                self.iface.messageBar().pushWarning("QgisBlender", "Choose an output file path.")
                return
            if not target_crs:
                self.iface.messageBar().pushWarning("QgisBlender", "Enter a target CRS (e.g. EPSG:3857).")
                return
            
            try:
                self.pipeline_v1(rasters, out_path, target_crs)
            except Exception as e: 
                self.iface.messageBar().pushCritical("Qgis2Blender", f"Failed: {e}")
                QgsMessageLog.logMessage(str(e), "QGIS2Blender", Qgis.Critical)
                raise

            # Confirm plugin is running
            #self.iface.messageBar().pushInfo(
            #    "QgisBlender",
            #    f"QGIS2Blender: {len(rasters)} raster(s) selected. CRS = {target_crs}"
            #)

            #print("QGIS2Blender output:", out_path)
            #print ("QGIS2Blender args:", step_args)







