# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisBlender
                                 A QGIS plugin
 This plugin prepares DEMs for use in Blender.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ben Leamon
        email                : ben.leamon@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import tempfile
import processing
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QListWidgetItem
from qgis.core import (
    QgsVectorLayer,
    QgsWkbTypes,
    QgsProject, 
    QgsRasterLayer,
    QgsCoordinateReferenceSystem,
    QgsCoordinateTransform,
    QgsMessageLog, 
    Qgis,
    QgsApplication,
    )

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .qgis_blender_dialog import QgisBlenderDialog


class QgisBlender:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QgisBlender_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QGIS2Blender')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Plugin Defaults
        self.default_gdal_args = {
            "merge": "",
            "warp": "",
            "clip": "",
            "translate": "-co COMPRESS=LZW -co TILED=YES"
        }

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QgisBlender', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = f'{self.plugin_dir}/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Prepare DEMs for Blender'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&QGIS2Blender'),
                action)
            self.iface.removeToolBarIcon(action)

    # Helper methods
    def ensure_proj_db(self):
        """Ensure PROJ can find proj.db for GDAL tools spawned by Processing."""
        if getattr(self, "_proj_ready", False):
            return

        # 1) If user/system already configured PROJ correctly, do nothing
        for var in ("PROJ_DATA", "PROJ_LIB"):
            p = os.environ.get(var)
            if p and os.path.exists(os.path.join(p, "proj.db")):
                self._proj_ready = True
                return

        # 2) Try QGIS-provided locations (portable)
        candidates = []
        try:
            candidates.append(os.path.join(QgsApplication.pkgDataPath(), "proj"))
            # common on some installs
            candidates.append(os.path.join(QgsApplication.prefixPath(), "share", "proj"))
        except Exception:
            pass

        # 3) Pick the first candidate that actually contains proj.db
        proj_dir = None
        for c in candidates:
            if c and os.path.exists(os.path.join(c, "proj.db")):
                proj_dir = c
                break

        if not proj_dir:
            raise RuntimeError(
                "Could not locate proj.db. Set PROJ_DATA to the folder containing proj.db "
                "or check your QGIS installation."
            )

        # 4) Set env vars for this QGIS session (inherited by gdalwarp subprocesses)
        os.environ.setdefault("PROJ_DATA", proj_dir)
        os.environ.setdefault("PROJ_LIB", proj_dir)  # compatibility

        QgsMessageLog.logMessage(
            f"Configured PROJ for session: PROJ_DATA={os.environ.get('PROJ_DATA')}",
            "QGIS2Blender",
            Qgis.Info
        )
        self._proj_ready = True

    def populate_raster_list(self):
        """Fill the dialog list with raster layers from the current project."""
        # Start by clearing the list
        self.dlg.listWidget_rasters.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsRasterLayer):
                item = QListWidgetItem(layer.name())
                item.setData(Qt.UserRole, layer)
                self.dlg.listWidget_rasters.addItem(item)

    def populate_mask_layer_combo(self):
        """Fill the AOI mask combo box with polygon vector layers."""
        self.dlg.comboBox_mask_layer.clear()

        # First option: no mask / no AOI clipping
        self.dlg.comboBox_mask_layer.addItem(
            "None — use full selected raster extent",
            None
        )

        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsVectorLayer):
                geom_type = QgsWkbTypes.geometryType(layer.wkbType())
                if geom_type == QgsWkbTypes.PolygonGeometry:
                    self.dlg.comboBox_mask_layer.addItem(layer.name(), layer)

    def populate_default_args(self):
        """Populate the dialog with default values"""
        self.dlg.plainTextEdit_merge_args.setPlainText(self.default_gdal_args["merge"])
        self.dlg.plainTextEdit_warp_args.setPlainText(self.default_gdal_args["warp"])
        self.dlg.plainTextEdit_clip_args.setPlainText(self.default_gdal_args["clip"])
        self.dlg.plainTextEdit_translate_args.setPlainText(self.default_gdal_args["translate"])

    def browse_output(self):
        """Open a save dialog and put the path into the output line"""
        path, _ = QFileDialog.getSaveFileName(
            self.dlg,
            "Save output GeoTIFF",
            "",
            "GeoTIFF (*.tif *.tiff)"
        )

        if path: 
            if not path.lower().endswith(('.tif', '.tiff')):
                path += ".tif"
            self.dlg.lineEdit_output.setText(path)
            
    def read_selected_rasters(self):
        items = self.dlg.listWidget_rasters.selectedItems()
        return [it.data(Qt.UserRole) for it in items]
    
    def read_step_args(self):
        return {
            "merge": self.dlg.plainTextEdit_merge_args.toPlainText().strip(),
            "warp": self.dlg.plainTextEdit_warp_args.toPlainText().strip(),
            "clip": self.dlg.plainTextEdit_clip_args.toPlainText().strip(),
            "translate": self.dlg.plainTextEdit_translate_args.toPlainText().strip(),
        }
    
    def build_vrt(self, raster_layers, workdir, merge_extra_args: str):
        """
        Build a virtual raster from 2+ input rasters and return the path.
        Uses gdal:buildvirtualraster.
        """
        sources = [layer.source() for layer in raster_layers]
        vrt_path = os.path.join(workdir, "00_mosaic.vrt")

        params = {
            "INPUT": sources,
            "RESOLUTION": 0,
            "SEPARATE": False,
            "OUTPUT": vrt_path,
        }

        merge_extra_args = (merge_extra_args or "").strip()
        if merge_extra_args:
            params["EXTRA"] = merge_extra_args

        res_vrt = processing.run("gdal:buildvirtualraster", params)
        QgsMessageLog.logMessage(f"VRT result: {res_vrt}", "QGIS2Blender", Qgis.Info)

        vrt_out = res_vrt.get("OUTPUT", vrt_path)
        if not os.path.exists(vrt_out):
            raise RuntimeError(f"VRT step did not create output: {vrt_out}")

        return vrt_out
    
    # Currently unused
    def compute_target_extent(self, target_crs):
        """Transform current canvas extent into the target CRS."""
        canvas = self.iface.mapCanvas()
        canvas_extent = canvas.extent()

        project = QgsProject.instance()
        canvas_crs = canvas.mapSettings().destinationCrs()

        xform = QgsCoordinateTransform(canvas_crs, target_crs, project)
        return xform.transformBoundingBox(canvas_extent)
    
    def read_mask_layer(self):
        """Return the selected polygon mask layer from the combo box."""
        idx = self.dlg.comboBox_mask_layer.currentIndex()
        if idx < 0:
            return None
        return self.dlg.comboBox_mask_layer.itemData(idx)   


    def step_warp(self, input_path, target_crs, warp_args, output_path):
        """Reproject input raster/VRT into target CRS."""
        warp_params = {
            "INPUT": input_path,
            "TARGET_CRS": target_crs.authid(),
            "EXTRA": warp_args,
            "OUTPUT": output_path,
        }

        res_warp = processing.run("gdal:warpreproject", warp_params)
        QgsMessageLog.logMessage(f"Warp result: {res_warp}", "QGIS2Blender", Qgis.Info)

        warp_out_actual = res_warp.get("OUTPUT", output_path)
        if not os.path.exists(warp_out_actual):
            raise RuntimeError(
                f"Warp step did not create output: {warp_out_actual}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return warp_out_actual
    
    def step_clip_by_mask(self, input_path, mask_layer, target_crs, clip_args, output_path):
        """Clip raster by polygon mask layer."""
        clip_params = {
            "INPUT": input_path,
            "MASK": mask_layer,
            "SOURCE_CRS": target_crs.authid(),
            "TARGET_CRS": target_crs.authid(),
            "NODATA": None,
            "ALPHA_BAND": False,
            "CROP_TO_CUTLINE": True,
            "KEEP_RESOLUTION": False,
            "SET_RESOLUTION": False,
            "X_RESOLUTION": None,
            "Y_RESOLUTION": None,
            "MULTITHREADING": False,
            "OPTIONS": "",
            "DATA_TYPE": 0,
            "EXTRA": clip_args,
            "OUTPUT": output_path,
        }

        res_clip = processing.run("gdal:cliprasterbymasklayer", clip_params)
        QgsMessageLog.logMessage(f"Mask clip result: {res_clip}", "QGIS2Blender", Qgis.Info)

        clip_out_actual = res_clip.get("OUTPUT", output_path)
        if not os.path.exists(clip_out_actual):
            raise RuntimeError(
                f"Mask clip step did not create output: {clip_out_actual}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return clip_out_actual
    
    # Currently unused. Replaced by step_clip_by_mask(). Keeping for future canvas AOI option. 
    def step_clip(self, input_path, target_extent, clip_args, output_path):
        """Clip raster by transformed canvas extent."""
        extent_str = (
            f"{target_extent.xMinimum()},"
            f"{target_extent.xMaximum()},"
            f"{target_extent.yMinimum()},"
            f"{target_extent.yMaximum()}"
        )

        clip_params = {
            "INPUT": input_path,
            "PROJWIN": extent_str,
            "EXTRA": clip_args,
            "OUTPUT": output_path,
        }

        res_clip = processing.run("gdal:cliprasterbyextent", clip_params)
        QgsMessageLog.logMessage(f"Clip result: {res_clip}", "QGIS2Blender", Qgis.Info)

        clip_out_actual = res_clip.get("OUTPUT", output_path)
        if not os.path.exists(clip_out_actual):
            raise RuntimeError(
                f"Clip step did not create output: {clip_out_actual}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return clip_out_actual
    
    def get_raster_min_max(self, raster_path):
        """Return min and max for band 1 of a raster."""
        layer = QgsRasterLayer(raster_path, "temp_stats_layer")
        if not layer.isValid():
            raise RuntimeError(f"Could not load raster for stats: {raster_path}")

        provider = layer.dataProvider()
        stats = provider.bandStatistics(1)

        min_val = stats.minimumValue
        max_val = stats.maximumValue

        if min_val == max_val:
            raise RuntimeError(
                f"Raster min and max are identical ({min_val}). Cannot rescale to 0-65535."
            )

        QgsMessageLog.logMessage(
            f"Raster stats for scaling: min={min_val}, max={max_val}",
            "QGIS2Blender",
            Qgis.Info
        )

        return min_val, max_val
    
    def read_nodata_fill_value(self):
        """
        Read optional NoData fill value from the dialog.

        Returns:
            None if blank, meaning: use valid raster minimum.
            float if the user entered a number.
        """
        text = self.dlg.lineEdit_nodata_fill.text().strip()

        if not text:
            return None

        try:
            return float(text)
        except ValueError:
            raise ValueError(
                f"Invalid NoData fill value: '{text}'. Please enter a number, or leave it blank."
            )
        
    def get_raster_nodata_value(self, raster_path):
        """Return band 1 NoData value, or None if no NoData value is set."""
        layer = QgsRasterLayer(raster_path, "temp_nodata_layer")
        if not layer.isValid():
            raise RuntimeError(f"Could not load raster for NoData check: {raster_path}")

        provider = layer.dataProvider()

        if provider.sourceHasNoDataValue(1):
            return provider.sourceNoDataValue(1)

        return None
    
    def step_fill_nodata_with_value(self, input_path, fill_value, output_path):
        """
        Replace NoData pixels with a chosen value before scaling.

        fill_value is in the DEM's original elevation units.
        """
        nodata = self.get_raster_nodata_value(input_path)

        if nodata is None:
            QgsMessageLog.logMessage(
                "No source NoData value found; skipping NoData fill step.",
                "QGIS2Blender",
                Qgis.Info
            )
            return input_path

        # Use GDAL raster calculator / gdal_calc.py.
        # where(A == nodata, fill_value, A)
        formula = f"where(A=={nodata}, {fill_value}, A)"

        params = {
            "INPUT_A": input_path,
            "BAND_A": 1,
            "FORMULA": formula,
            "NO_DATA": None,
            "RTYPE": 5,  # Float32 in many QGIS/GDAL Processing versions
            "OPTIONS": "",
            "EXTRA": "--hideNoData",
            "OUTPUT": output_path,
        }

        QgsMessageLog.logMessage(
            f"Filling NoData: nodata={nodata}, fill_value={fill_value}, formula={formula}",
            "QGIS2Blender",
            Qgis.Info
        )

        res = processing.run("gdal:rastercalculator", params)
        filled_out = res.get("OUTPUT", output_path)

        if not os.path.exists(filled_out):
            raise RuntimeError(
                f"NoData fill step did not create output: {filled_out}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return filled_out

    def step_translate(self, input_path, translate_args, output_path, do_scale=True):
        """Translate raster to final output path, optionally scaling to UInt16."""
        extra_args = (translate_args or "").strip()

        if do_scale:
            min_val, max_val = self.get_raster_min_max(input_path)
            scale_args = f"-scale {min_val} {max_val} 0 65535 -ot UInt16"
            extra_args = f"{scale_args} {extra_args}".strip()

        translate_params = {
            "INPUT": input_path,
            "EXTRA": extra_args,
            "OUTPUT": output_path,
        }

        res_translate = processing.run("gdal:translate", translate_params)
        QgsMessageLog.logMessage(f"Translate result: {res_translate}", "QGIS2Blender", Qgis.Info)

        final_out = res_translate.get("OUTPUT", output_path)
        if not os.path.exists(final_out):
            raise RuntimeError(
                f"Translate step did not create output: {final_out}\n"
                "Check Log Messages → Processing for GDAL error details."
            )

        return final_out


    def pipeline_v1(self, raster_layers, out_path: str, target_crs_text: str, mask_layer):
        """
        Version 1 pipeline:
        optional VRT -> warp -> clip -> translate
        """
        self.ensure_proj_db()
        step_args = self.read_step_args()

        target_crs = QgsCoordinateReferenceSystem(target_crs_text)
        if not target_crs.isValid():
            raise ValueError(f"Invalid CRS: '{target_crs_text}'. Please use an EPSG code.")

        workdir = tempfile.mkdtemp(prefix="qgis_blender_")
        QgsMessageLog.logMessage(f"Workdir: {workdir}", "QGIS2Blender", Qgis.Info)
        QgsMessageLog.logMessage(f"Target CRS: {target_crs.authid()}", "QGIS2Blender", Qgis.Info)

        # Decide what feeds the warp step
        if len(raster_layers) == 1:
            warp_input = raster_layers[0].source()
        else:
            warp_input = self.build_vrt(raster_layers, workdir, step_args["merge"])

        warp_out = os.path.join(workdir, "01_warp.tif")
        clip_out = os.path.join(workdir, "02_clip.tif")

        warped = self.step_warp(warp_input, target_crs, step_args["warp"], warp_out)

        if mask_layer is not None:
            clipped_or_warped = self.step_clip_by_mask(
                warped,
                mask_layer,
                target_crs,
                step_args["clip"],
                clip_out
            )
        else:
            QgsMessageLog.logMessage(
                "No AOI mask selected; exporting full warped raster/mosaic extent.",
                "QGIS2Blender",
                Qgis.Info
            )
            clipped_or_warped = warped

        # Fill NoData before scaling/export
        user_fill_value = self.read_nodata_fill_value()

        if user_fill_value is None:
            # Blank field = use valid raster minimum
            min_val, _ = self.get_raster_min_max(clipped_or_warped)
            fill_value = min_val
        else:
            fill_value = user_fill_value

        filled_out = os.path.join(workdir, "03_filled_nodata.tif")
        filled = self.step_fill_nodata_with_value(
            clipped_or_warped,
            fill_value,
            filled_out
        )
        filled_min, filled_max = self.get_raster_min_max(filled)
        #Add logging 
        QgsMessageLog.logMessage(
            f"After NoData fill: min={filled_min}, max={filled_max}, fill_value={fill_value}",
            "QGIS2Blender",
            Qgis.Info
        )

        final_out = self.step_translate(
            filled,
            step_args["translate"],
            out_path
        )

        out_layer = QgsRasterLayer(final_out, os.path.basename(final_out))
        if not out_layer.isValid():
            raise RuntimeError("Output file was written but QGIS could not load it as a raster layer.")

        QgsProject.instance().addMapLayer(out_layer)
        self.iface.messageBar().pushSuccess("QGIS2Blender", "Created output and added to project.")

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        if self.first_start == True:
            self.first_start = False
            self.dlg = QgisBlenderDialog()
            # Populate defaults 
            self.populate_default_args()

            # Connect dialog buttons to widgets
            self.dlg.pushButton_browse.clicked.connect(self.browse_output)

        # Refresh the list of rasters each time the dialog opens
        self.populate_raster_list()
        # Refresh the list of clipping layers each time the dialog opens 
        self.populate_mask_layer_combo()
        # Show the dialog
        self.dlg.show()
        # Run the dialog event loop
        result = self.dlg.exec_()
        
        # See if OK was pressed
        if result:
            rasters = self.read_selected_rasters()
            out_path = self.dlg.lineEdit_output.text().strip()
            target_crs = self.dlg.lineEdit_target_crs.text().strip()
            mask_layer = self.read_mask_layer()

            if not rasters:
                self.iface.messageBar().pushWarning("QgisBlender", "Select at least one raster layer.")
                return
            if not out_path:
                self.iface.messageBar().pushWarning("QgisBlender", "Choose an output file path.")
                return
            if not target_crs:
                self.iface.messageBar().pushWarning("QgisBlender", "Enter a target CRS (e.g. EPSG:3857).")
                return
            # I think we don't actually want this... just default to using the whole DEM if no clip-mask.
            # if mask_layer is None:
            #     self.iface.messageBar().pushWarning(
            #         "QGIS2Blender",
            #         "Select a polygon mask layer for the AOI."
            #     )
            #     return
            
            try:
                self.pipeline_v1(rasters, out_path, target_crs, mask_layer)
            except Exception as e: 
                self.iface.messageBar().pushCritical("Qgis2Blender", f"Failed: {e}")
                QgsMessageLog.logMessage(str(e), "QGIS2Blender", Qgis.Critical)
                raise

            # Confirm plugin is running
            #self.iface.messageBar().pushInfo(
            #    "QgisBlender",
            #    f"QGIS2Blender: {len(rasters)} raster(s) selected. CRS = {target_crs}"
            #)

            #print("QGIS2Blender output:", out_path)
            #print ("QGIS2Blender args:", step_args)