# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QgisBlender
                                 A QGIS plugin
 This plugin prepares DEMs for use in Blender.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-02-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Ben Leamon
        email                : ben.leamon@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QListWidgetItem
from qgis.core import QgsProject, QgsRasterLayer

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .qgis_blender_dialog import QgisBlenderDialog
import os.path


class QgisBlender:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'QgisBlender_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&QGIS2Blender')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None
        
        # Plugin Defaults
        self.default_gdal_args = {
            "merge": "",
            "warp": "",
            "clip": "",
            "translate": "-co COMPRESS=LZW -co TILED=YES"
        }

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('QgisBlender', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToRasterMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/qgis_blender/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Prepare DEMs for Blender'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginRasterMenu(
                self.tr(u'&QGIS2Blender'),
                action)
            self.iface.removeToolBarIcon(action)

    # Helper methods
    def populate_raster_list(self):
        """Fill the dialog list with raster layers from the current project."""
        # Start by clearing the list
        self.dlg.listWidget_rasters.clear()

        for layer in QgsProject.instance().mapLayers().values():
            if isinstance(layer, QgsRasterLayer):
                item = QListWidgetItem(layer.name())
                item.setData(256, layer)
                self.dlg.listWidget_rasters.addItem(item)

    def populate_default_args(self):
        """Populate the dialog with default values"""
        self.dlg.plainTextEdit_merge_args.setPlainText(self.default_gdal_args["merge"])
        self.dlg.plainTextEdit_warp_args.setPlainText(self.default_gdal_args["warp"])
        self.dlg.plainTextEdit_clip_args.setPlainText(self.default_gdal_args["clip"])
        self.dlg.plainTextEdit_translate_args.setPlainText(self.default_gdal_args["translate"])

    def browse_output(self):
        """Open a save dialog and put the path into the output line"""
        path, _ = QFileDialog.getSaveFileName(
            self.dlg,
            "Save output GeoTIFF",
            "",
            "GeoTIFF (*.tif *.tiff)"
        )

        if path: 
            if not path.lower().endswith(('.tif', '.tiff')):
                path += ".tif"
            self.dlg.lineEdit_output.setText(path)
            
    def read_selected_rasters(self):
        items = self.dlg.listWidget_rasters.selectedItems()
        return[it.data(Qt.UserRole) for it in items]
    
    def read_step_args(self):
        return{
            "merge": self.dlg.plainTextEdit_merge_args.toPlainText().strip(),
            "warp": self.dlg.plainTextEdit_warp_args.toPlainText().strip(),
            "clip": self.dlg.plainTextEdit_clip_args.toPlainText().strip(),
            "translate": self.dlg.plainTextEdit_translate_args.toPlainText().strip(),
        }

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = QgisBlenderDialog()

            # Connect dialog buttons to widgets
            self.dlg.pushButton_browse.clicked.connect(self.browse_output)

        # Refresh the list of rasters each time the dialog opens
        self.populate_raster_list()

        # show the dialog
        self.dlg.show()
        # Populate defaults 
        self.populate_default_args()
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # Confirm plugin is running
            self.iface.messageBar().pushInfo("QgisBlender", "Hello!")

            selected_items = self.dlg.listWidget_rasters.selectedItems()
            rasters = [item.data(256) for item in selected_items]
            out_path = self.dlg.lineEdit_output.text().strip()

            if not rasters:
                self.iface.messageBar().pushWarning(
                    "Qgis2Blender",
                    "Please select at least one raster layer."
                )
                return
            
            if not out_path:
                self.iface.messageBar().pushWarning(
                    "Qgis2Blender",
                    "Please choose an output file path."
                )

            # Debug: confirm we can read the inputs: 
            raster_names = ", ".join([r.name() for r in rasters])
            self.iface.messageBar().pushInfo(
                "Qgis2Blender",
                f"Selected {len(rasters)} raster(s): {raster_names}"
            )

            print("[Qgis2Blender] Output path:", out_path)





